

###部门查询
GET http://localhost:8080/departman/30

###添加部门
POST http://localhost:8080/departments
Content-Type: application/json

{
  "dname":"无敌部",
    "loc":"辽宁"
}

###修改部门
PUT http://localhost:8080/employees/transfer?empno=16&deptno=40

###部门删除
DELETE http://localhost:8080/departman/70



