###部门查询
GET http://localhost:8080/departments/30

###添加部门
POST http://localhost:8080/departments
Content-Type: application/json

{
  "dname":"无敌部",
    "loc":"辽宁"
}

###部门删除
DELETE http://localhost:8080/departments/110

###修改部门信息
PUT http://localhost:8080/departments
Content-Type: application/json

{
  "deptno": 90,
  "dname":"无敌部",
  "loc":"上海"
}



